### ISSUE TITLE
Fix internal error issue when editing a student from the view button

### ISSUE THREAD

**Issue by Bam92** [Bam92/attendancy-gda#114]
When you click "Modifier" button, you get an error.
![edit-student](https://user-images.githubusercontent.com/14941675/211900204-062bec7f-da67-4ef0-aa8b-62049bded700.png)

**Comment by Cedric921** [comment]
I work on this issue

**Comment by Bam92** [comment]
Still working?

**Comment by Bam92** [comment]
Why do you work on so many things at once? Try to work on small pieces, pls.
