### ISSUE TITLE
Show toast message when a student is added

### ISSUE THREAD

**Issue by Bam92** [Bam92/attendancy-gda#126]

**Comment by h3vanth** [comment]
@Bam92 I believe this is already a part of #119

**Comment by Bam92** [comment]
It does not work. Have you tried it with students ("apprenants") ?

**Comment by Bam92** [comment]
I see why it was not working. The redirection was being made before the toast message. Now fixed
![flash-student-add](https://user-images.githubusercontent.com/14941675/212623607-549e98e4-2b26-4385-b6a8-14ad965684aa.png)
