### ISSUE TITLE
Redesign list (users, students)

### ISSUE THREAD

**Issue by Bam92** [Bam92/attendancy-gda#73]
Get inspiration
- https://dribbble.com/shots/15269184-Tickets-Admin-Panel-Dashboard/attachments/7021133?mode=media
- https://dribbble.com/shots/15135060-BoltCard-Fund-Request
- ![attendance-tracker-inspiration-table-header-last-col](https://user-images.githubusercontent.com/14941675/210738233-9889beb4-6c93-4cd3-848e-fffdeca0928a.png)

Any idea? @Cedric921

**Comment by JoeMakuta** [comment]
Currently working on this isue!

**Comment by Bam92** [comment]
WIP
![list-of-student](https://user-images.githubusercontent.com/14941675/211302168-edb61959-588d-4efd-831e-20345ec9c7e9.png)

**Comment by JoeMakuta** [comment]
Dear @Bam92 , Merge my last PR everything is in!

**Comment by Bam92** [comment]
Which one?
