### ISSUE TITLE
refactor views/includes

### ISSUE THREAD

**Issue by Bam92** [Bam92/attendancy-gda#86]
- rename` header.ejs` --> `navigation.ejs`
- rename `head.ejs` --> `header.ejs`
- etc.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by Bam92** [comment]
You can go on @tarunsamanta2k20. Sorry, I missed your comment.

**Comment by tarunsamanta2k20** [comment]
@Bam92 Created a PR
